import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";

import SubPocketSendMoneyPage from "./singleSendMoneySubPocketPage";
import LoginPage from "../login/loginPage";


/* NAVIGATION */
Given("I am logged into the Sub Pocket Dashboard", () => {
    cy.viewport(1800, 1000);
    const url = Cypress.expose('baseUrl');

    cy.visit(url);

    LoginPage.enterSubPocketEmail();
    LoginPage.enterSubPocketPassword();
    LoginPage.clickSignIn();
});

Given("I navigate to the Send Money page", () => {
    SubPocketSendMoneyPage.openSendMoney();
});


/* ============================
   PAGE LOAD & LAYOUT
   ============================ */

Then("I should see the Send Money page title", () => {
    SubPocketSendMoneyPage.validatePageTitle();
});

Then("the Single tab should be active", () => {
    SubPocketSendMoneyPage.validateSingleTabActive();
});

Then("I should see the {string} section", (sectionTitle) => {
    cy.contains(sectionTitle).should("be.visible");
});

Then("I should see the source pocket dropdown", () => {
    SubPocketSendMoneyPage.validateSourcePocketDropdown();
});

Then("I should see the Account number input field", () => {
    SubPocketSendMoneyPage.validateAccountNumberField();
});

Then("I should see the Select bank dropdown", () => {
    SubPocketSendMoneyPage.validateSelectBankDropdown();
});

Then("I should see the Account name field", () => {
    SubPocketSendMoneyPage.validateAccountNameField();
});

Then("I should see the Amount input field", () => {
    SubPocketSendMoneyPage.validateAmountField();
});

Then("I should see the Narration input field", () => {
    SubPocketSendMoneyPage.validateNarrationField();
});


/* ============================
   SOURCE POCKET
   ============================ */

Then("the source pocket should display a pocket ID", () => {
    SubPocketSendMoneyPage.validatePocketId();
});

Then("the source pocket should display a balance", () => {
    SubPocketSendMoneyPage.validatePocketBalance();
});


/* ============================
   FORM ACTIONS
   ============================ */

When("I enter account number {string}", (accountNumber) => {
    SubPocketSendMoneyPage.enterAccountNumber(accountNumber);
});

When("I select a bank", () => {
    SubPocketSendMoneyPage.selectBank();
});

When("I enter amount {string}", (amount) => {
    SubPocketSendMoneyPage.enterAmount(amount);
});

When("I enter narration {string}", (narration) => {
    SubPocketSendMoneyPage.enterNarration(narration);
});

When("I click the Continue button", () => {
    SubPocketSendMoneyPage.clickContinue();
});

When("I click the Cancel button", () => {
    SubPocketSendMoneyPage.clickCancel();
});


/* ============================
   FORM VALIDATION — BANK TRANSFER
   ============================ */

Then("the Continue button should be disabled", () => {
    SubPocketSendMoneyPage.validateContinueDisabled();
});

Then("the account name should be auto-generated", () => {
    SubPocketSendMoneyPage.validateAccountNameAutoGenerated();
});

Then("the account number field should contain only 10 digits", () => {
    SubPocketSendMoneyPage.validateAccountNumberMaxLength();
});


/* ============================
   TRANSACTION CONFIRMATION
   ============================ */

Then("I should see the transaction confirmation page", () => {
    SubPocketSendMoneyPage.validateTransactionConfirmation();
});

When("I click the Continue button on confirmation page", () => {
    SubPocketSendMoneyPage.clickContinueOnConfirmation();
});


/* ============================
   OTP VERIFICATION
   ============================ */

Then("I should see the OTP verification page", () => {
    SubPocketSendMoneyPage.validateOtpPage();
});

When("I enter the OTP {string}", (otp) => {
    SubPocketSendMoneyPage.enterOtp(otp);
});

Then("all OTP fields should be filled", () => {
    SubPocketSendMoneyPage.validateOtpFieldsFilled();
});

When("I click the Continue button after OTP", () => {
    SubPocketSendMoneyPage.clickContinueAfterOtp();
});

Then("I should see the invalid OTP error message", () => {
    SubPocketSendMoneyPage.validateInvalidOtpError();
});

Then("I should see a successful transaction page", () => {
    SubPocketSendMoneyPage.validateSuccessfulTransaction();
});

Then("I should see the insufficient balance error", () => {
    SubPocketSendMoneyPage.validateInsufficientBalanceError();
});


/* ============================
   CANCEL
   ============================ */

Then("the send money form should be cleared", () => {
    SubPocketSendMoneyPage.validateFormCleared();
})
